@api = https://localhost:5001

### add tag
POST {{api}}/tag
Content-Type: application/json

{
  "description": "Mniam!"
}

### get tags
GET {{api}}/tags
Content-Type: application/json

### get tag id
GET {{api}}/tag/6986edae-5428-449b-aa7c-110f3753b70b
Content-Type: application/json

### delete tag
DELETE {{api}}/tag/22AE87F1-C3A2-4F5A-A6D7-ED0833442545
Content-Type: application/json

### update tag
PUT {{api}}/tag/48ce944a-740d-4cae-82ba-f9984a919426
Content-Type: application/json

{
"description": "Pyszne!"
}